### ISSUE TITLE
AssertionError: Expected 0x08

### ISSUE THREAD

**Issue by wen008** [Ayyoubzadeh/Micropython-ESP32-W5500--Wiznet-#1]
![image](https://user-images.githubusercontent.com/45958967/186860328-864df2b0-136a-4137-9d57-3443806d4c9f.png)

**Comment by Ayyoubzadeh** [comment]
Check the wiring

**Comment by wen008** [comment]
wiring no problem but..

**Comment by wen008** [comment]
![image](https://user-images.githubusercontent.com/45958967/187185561-58582c3a-d11e-405f-a2cf-340185c592f5.png)

**Comment by Ayyoubzadeh** [comment]
> wiring no problem but..

![image](https://user-images.githubusercontent.com/92551110/187185939-a50178a5-a85e-4598-86a5-efd8f9aa4957.png)
ref:https://forum.micropython.org/viewtopic.php?t=5851&start=10

**Comment by caginagirdemir** [comment]
change SPI init line like this
self._device.init(baudrate=500000, polarity=0, phase=0, bits=8, firstbit=0, sck=Pin(18), mosi=Pin(23), miso=Pin(19)) #baudrate=500000
