### ISSUE TITLE
post or get timeout??

### ISSUE THREAD

**Issue by one0410** [Ayyoubzadeh/Micropython-ESP32-W5500--Wiznet-#3]
Hi,

I appreciate for your project.
If the server down or doesn't exist, requests.post or get will hang for a long time.
Do you have any ideas how I can set a timeout for request to server???

**Comment by Ayyoubzadeh** [comment]
Hello,

Thank you.

Check the settimeout function in line #409 of wiznet5k_socket.py

Regards,

S.M.Ayyoubzadeh

**Comment by one0410** [comment]
Thx for your quickly response.
Finally, I pass the timeout param into request function.
But when I pass 5 seconds, it takes about 30 secs.

**Comment by Ayyoubzadeh** [comment]
Hello,
You're Welcome.

Try a lower value, for example, 1 second, and adjust the value.

Regards,
S.M.Ayyoubzadeh
